export const SITE_CONTENT_DEFAULTS: Record<string, string> = {
  brand_name: 'First Line Transfer',
  logo_url: '/logo.png',
  site_meta_title: 'First Line Transfer - Преміум трансфер без компромісів',
  site_meta_description: 'Преміальні трансфери Європою та Україною на автомобілях VIP-класу. Онлайн бронювання, професійні водії, комфорт і конфіденційність.',
  site_meta_keywords: 'трансфер, VIP трансфер, оренда авто з водієм, преміум трансфер, Mercedes S-Class, Україна, Європа',
  site_og_title: 'First Line Transfer - Преміум трансфер',
  site_og_description: 'Ваш час. Ваші правила. Ідеальний сервіс від дверей до дверей.',
  site_url: 'https://first-line-transfer.com',
  schema_description: 'Преміум трансфер на авто VIP-класу.',
  schema_price_range: '€€€',
  schema_address_city: 'Kyiv',
  schema_address_country: 'UA',
  schema_area_served: 'UA,PL,DE,CZ,AT,HU,SK',

  menu_services: 'Послуги',
  menu_fleet: 'Автопарк',
  menu_gallery: 'Галерея',
  menu_contact: 'Контакти',
  menu_login: 'Увійти',
  menu_profile: 'Профіль',
  menu_driver_cabinet: 'Кабінет водія',
  menu_logout: 'Вийти',
  menu_calculator: 'Бронювання',
  menu_home: 'Головна',
  btn_book_now: 'Бронювати',
  btn_hero_cta: 'Розрахувати вартість',
  loading_calculator: 'Завантаження калькулятора...',

  hero_title: 'Преміум *трансфер*\nбез компромісів',
  hero_subtitle: 'Ваш час. Ваші правила. Ідеальний сервіс від дверей до дверей з гарантованою пунктуальністю.',
  hero_bg_image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80',
  hero_bg_video: '',

  services_title: 'Чому обирають *нас*?',
  feature_1_icon: 'Clock',
  feature_1_title: 'Пунктуальність',
  feature_1_desc: 'Ми завжди прибуваємо за 15 хвилин до вказаного часу.',
  feature_2_icon: 'Car',
  feature_2_title: 'Преміум автопарк',
  feature_2_desc: 'Тільки нові автомобілі в ідеальному технічному стані.',
  feature_3_icon: 'ShieldCheck',
  feature_3_title: 'Конфіденційність',
  feature_3_desc: 'Повна гарантія анонімності та безпеки ваших поїздок.',
  feature_4_icon: 'Award',
  feature_4_title: 'Професійні водії',
  feature_4_desc: 'Англомовні водії з багаторічним досвідом VIP-обслуговування.',

  gallery_title: 'Галерея',
  gallery_fallback_alt: 'Фото автопарку',
  empty_legs_title: 'Гарячі пропозиції *Empty Legs*',
  empty_legs_anywhere: 'Будь-яке',
  empty_legs_book_button: 'Забронювати зі знижкою',

  contact_section_title: "Зв'яжіться з нами",
  contact_section_subtitle: "Залиште свої контакти, і ми зв'яжемося з вами найближчим часом. Ви також можете задати будь-яке запитання.",
  contact_success_title: 'Дякуємо за звернення!',
  contact_success_message: "Ваше повідомлення відправлено. Ми скоро з вами зв'яжемося.",
  contact_name_label: "Ім'я *",
  contact_name_placeholder: "Ваше ім'я",
  contact_phone_label: 'Телефон *',
  contact_phone_placeholder: '+380...',
  contact_email_label: 'Email *',
  contact_email_placeholder: 'Ваш email',
  contact_message_label: 'Повідомлення *',
  contact_message_placeholder: 'Ваше питання...',
  contact_submit: 'Відправити запит',
  contact_submitting: 'Відправка...',
  contact_phone: '+380 00 000 00 00',
  contact_email: 'info@firstline.com',

  footer_text: 'Преміальні трансфери Європою та Україною. Комфорт, безпека та конфіденційність.',
  footer_menu_title: 'Меню',
  footer_contacts_title: 'Контакти',
  footer_rights: 'Всі права захищено.',

  fuel_price_uah: '60',
  eur_to_uah_rate: '42.5',
  weekend_coefficient: '1.2',
  child_seat_fee: '15',
  animal_fee: '20',
  meet_and_greet_fee: '15',
  luggage_medium_fee: '10',
  luggage_large_fee: '20',
  amortization_rate: '0.05',
  margin_rate: '0.2',
  delivery_rate: '15',
  base_location_lat: '49.8397',
  base_location_lng: '24.0297',

  admin_brand_title: 'Car CRM',
  admin_brand_subtitle: 'Admin workspace',
  admin_open_site: 'Відкрити сайт',
  admin_group_operations: 'Операції',
  admin_group_fleet: 'Автопарк',
  admin_group_clients: 'Клієнти',
  admin_group_content: 'Контент',
  admin_group_finance: 'Фінанси',
  admin_group_system: 'Система',
  admin_nav_dashboard: 'Дашборд',
  admin_nav_dashboard_desc: 'Що потребує уваги',
  admin_nav_bookings: 'Заявки і календар',
  admin_nav_bookings_desc: 'Рейси, статуси, водії',
  admin_nav_chat: 'Повідомлення',
  admin_nav_chat_desc: 'Web, Telegram, Messenger',
  admin_nav_fleet: 'Авто і медіа',
  admin_nav_fleet_desc: 'Машини, тарифи, галерея',
  admin_nav_promotions: 'Empty Legs',
  admin_nav_promotions_desc: 'Знижки на порожні рейси',
  admin_nav_users: 'Клієнти, водії, ролі',
  admin_nav_users_desc: 'Доступи, паролі, ставки',
  admin_nav_feedback: "Зворотний зв'язок",
  admin_nav_feedback_desc: 'Форми з сайту',
  admin_nav_cms: 'Редактор сайту',
  admin_nav_cms_desc: 'Сторінки, блоки, SEO',
  admin_nav_invoices: 'Рахунки',
  admin_nav_invoices_desc: 'Інвойси і оплати',
  admin_nav_settings: 'Налаштування CRM',
  admin_nav_settings_desc: 'Інтеграції, валюти, пальне',

  telegram_enabled: 'false',
  telegram_bot_token: '',
  telegram_api_id: '',
  telegram_api_hash: '',
  telegram_string_session: '',
  facebook_enabled: 'false',
  facebook_page_id: '',
  facebook_verify_token: '',
  facebook_page_access_token: '',
  whatsapp_enabled: 'false',
  whatsapp_phone_number_id: '',
  whatsapp_business_account_id: '',
  whatsapp_access_token: '',
  payment_card: '',
  payment_usdt: '',
};

export function withContentDefaults(content: Record<string, string> = {}) {
  return {
    ...SITE_CONTENT_DEFAULTS,
    ...content,
  };
}

export function getMissingContentDefaults(content: Record<string, string>) {
  return Object.entries(SITE_CONTENT_DEFAULTS).filter(([key]) => !(key in content));
}
