version: '3.8'
services:
  db:
    image: 'postgres:15-alpine'
    container_name: carcrm_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: carcrm
    expose:
      - '5432'
    volumes:
      - 'db_data:/var/lib/postgresql/data'
  web:
    build:
      context: ./carcrm
      dockerfile: Dockerfile
    container_name: carcrm_web
    restart: always
    expose:
      - '3000'
    depends_on:
      - db
    environment:
      - 'DATABASE_URL=postgresql://admin:admin_password@db:5432/carcrm?schema=public'
      - 'NEXTAUTH_URL=https://firstline.texno.plus'
      - 'NEXTAUTH_SECRET=VipCarSecretKey2026!'
      - 'TELEGRAM_BOT_TOKEN='
      - 'TELEGRAM_CHAT_ID='
volumes:
  db_data: null
