ALTER TABLE "Driver"
ADD COLUMN "salaryPerHour" DOUBLE PRECISION NOT NULL DEFAULT 12.0,
ADD COLUMN "dailyAllowance" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN "overnightAllowance" DOUBLE PRECISION NOT NULL DEFAULT 90.0;

ALTER TABLE "Car"
ADD COLUMN "includedPassengers" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "amortizationPerKm" DOUBLE PRECISION NOT NULL DEFAULT 0.08,
ADD COLUMN "deliveryBaseFee" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN "allowsChildren" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "allowsAnimals" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Booking"
ADD COLUMN "desiredArrivalAt" TIMESTAMP(3),
ADD COLUMN "pickupAt" TIMESTAMP(3),
ADD COLUMN "carDispatchAt" TIMESTAMP(3),
ADD COLUMN "estimatedArrivalAt" TIMESTAMP(3),
ADD COLUMN "routeDurationMins" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "deliveryDurationMins" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "prepBufferMins" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "customsWaitHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "manualWaitingHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "trafficBufferPercent" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN "billableHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "timeCost" DOUBLE PRECISION,
ADD COLUMN "hotelCost" DOUBLE PRECISION,
ADD COLUMN "surcharges" DOUBLE PRECISION,
ADD COLUMN "pricingSnapshot" JSONB,
ADD COLUMN "childSeats" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "petsCount" INTEGER NOT NULL DEFAULT 0;
